import { integer, pgTable, primaryKey, text } from "drizzle-orm/pg-core";
import { sourceEquipment, sourceExercises, sourceMuscles } from "./source";

/**
 * Derived layer: normalised out of source_exercises' free-text fields so muscle
 * and equipment filters are indexable joins rather than string parsing at query
 * time. Fully regenerated by the import pipeline on every run — never hand-edited.
 */

export const exerciseMuscles = pgTable(
  "exercise_muscles",
  {
    exerciseId: text("exercise_id")
      .notNull()
      .references(() => sourceExercises.exerciseId),
    muscleId: text("muscle_id")
      .notNull()
      .references(() => sourceMuscles.muscleId),
    /** "primary" | "secondary" | "stabilizer" — stabilizer is unused until the
     * source data populates Stabilizer Muscles, but the model already supports it. */
    role: text("role").notNull(),
  },
  (t) => [primaryKey({ columns: [t.exerciseId, t.muscleId, t.role] })],
);

export const exerciseEquipment = pgTable(
  "exercise_equipment",
  {
    exerciseId: text("exercise_id")
      .notNull()
      .references(() => sourceExercises.exerciseId),
    equipmentId: text("equipment_id")
      .notNull()
      .references(() => sourceEquipment.equipmentId),
  },
  (t) => [primaryKey({ columns: [t.exerciseId, t.equipmentId] })],
);

/**
 * Parsed out of the Source Exercises Variations / Alternative Exercises /
 * Progression / Regression columns (format: "label | url; label2 | url2").
 * These are human-curated links from the original source, distinct from the
 * rule-derived source_relationships candidates. `toExerciseId` is populated
 * when the linked URL matches another row's url exactly; otherwise the link
 * is kept as label + url only rather than dropped.
 */
export const exerciseLinks = pgTable("exercise_links", {
  id: integer("id").generatedAlwaysAsIdentity().primaryKey(),
  fromExerciseId: text("from_exercise_id")
    .notNull()
    .references(() => sourceExercises.exerciseId),
  relationType: text("relation_type").notNull(), // "variation" | "alternative" | "progression" | "regression"
  label: text("label").notNull(),
  url: text("url"),
  toExerciseId: text("to_exercise_id").references(() => sourceExercises.exerciseId),
});
