import type { MetadataRoute } from "next";

/**
 * Powers "Add to Home Screen" on Android/Chrome and the desktop install
 * prompt. iOS instead uses apple-icon.png (a separate convention, no
 * manifest involved) — both point at the same teal dumbbell mark used in
 * the top bar, generated by scripts/generate-app-icons.mjs.
 *
 * display: "standalone" so a home-screen launch opens without browser
 * chrome, the actual point of "saving it to your desktop" on a phone.
 * start_url still goes through the normal site password gate (src/proxy.ts)
 * — the manifest only affects how the icon launches, not auth.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Exercise Partner",
    short_name: "Exercise Partner",
    description: "A personal exercise knowledge base and workout platform.",
    start_url: "/",
    display: "standalone",
    background_color: "#ffffff",
    theme_color: "#0f766e",
    icons: [
      { src: "/icon-192.png", sizes: "192x192", type: "image/png" },
      { src: "/icon-512.png", sizes: "512x512", type: "image/png" },
    ],
  };
}
