import { getAdminSessionStatus } from "@/app/admin/login/actions";
import { redirect } from "next/navigation";
import { readFile } from "fs/promises";
import { join } from "path";

interface ImplementedItem {
  idea: string;
  whatItDoes: string;
  shipped: string;
}

interface NotYetImplementedItem {
  idea: string;
  whatItDoes: string;
  whyItFits: string;
  effort: string;
}

interface RejectedDeferredItem {
  idea: string;
  decision: string;
  reasoning: string;
}

interface EnhancementsData {
  implemented: ImplementedItem[];
  notYetImplemented: { category: string; items: NotYetImplementedItem[] }[];
  rejectedDeferred: RejectedDeferredItem[];
}

/**
 * public/enhancements.json is generated by npm run docs (scripts/docs/
 * enhancements.ts's generateEnhancementsJson) from the exact same data as
 * ENHANCEMENTS.docx, so the two can no longer drift the way they did for
 * over a month before this was fixed (PROJECT_PLAN.docx section 4, item 57).
 * Do not hand-edit this file — edit scripts/docs/enhancements.ts and
 * regenerate.
 */
async function getEnhancements(): Promise<EnhancementsData> {
  const filePath = join(process.cwd(), "public", "enhancements.json");
  const content = await readFile(filePath, "utf-8");
  return JSON.parse(content);
}

export default async function EnhancementsPage() {
  const isAdmin = await getAdminSessionStatus();
  if (!isAdmin) {
    redirect("/admin/login");
  }

  const enhancements = await getEnhancements();

  return (
    <div className="space-y-8 p-6">
      <div className="space-y-2">
        <h1 className="text-h2 font-semibold text-foreground">Enhancements</h1>
        <p className="text-small text-muted-foreground">Product roadmap and feature status</p>
      </div>

      {/* Implemented */}
      <section className="space-y-4">
        <div className="space-y-1">
          <h2 className="text-h3 font-semibold text-foreground">Implemented</h2>
          <p className="text-small text-muted-foreground">Ideas beyond the core plan that shipped along the way</p>
        </div>
        <div className="space-y-2">
          {enhancements.implemented.map((item, idx) => (
            <div key={idx} className="flex items-start justify-between gap-4 rounded-lg border border-border bg-card p-4">
              <div>
                <p className="font-medium text-foreground">{item.idea}</p>
                <p className="text-small text-muted-foreground">{item.whatItDoes}</p>
              </div>
              <span className="inline-flex shrink-0 items-center rounded-full bg-accent px-3 py-1 text-small font-medium text-accent-foreground">
                {item.shipped}
              </span>
            </div>
          ))}
        </div>
      </section>

      {/* Not Yet Implemented */}
      <section className="space-y-6">
        <div className="space-y-1">
          <h2 className="text-h3 font-semibold text-foreground">Not Yet Implemented</h2>
          <p className="text-small text-muted-foreground">Candidates, not commitments — grouped as in ENHANCEMENTS.docx</p>
        </div>
        {enhancements.notYetImplemented.map((group) => (
          <div key={group.category} className="space-y-2">
            <h3 className="text-body font-medium text-foreground">{group.category}</h3>
            {group.items.map((item, idx) => (
              <div key={idx} className="flex items-start justify-between gap-4 rounded-lg border border-border bg-card p-4">
                <div>
                  <p className="font-medium text-foreground">{item.idea}</p>
                  <p className="text-small text-muted-foreground">{item.whatItDoes}</p>
                </div>
                <span className="inline-flex shrink-0 items-center rounded-full bg-muted px-3 py-1 text-small font-medium text-muted-foreground">
                  {item.effort}
                </span>
              </div>
            ))}
          </div>
        ))}
      </section>

      {/* Rejected / Deferred */}
      <section className="space-y-4">
        <div className="space-y-1">
          <h2 className="text-h3 font-semibold text-foreground">Rejected / Deferred</h2>
          <p className="text-small text-muted-foreground">Recorded with reasoning so these aren&apos;t re-litigated later</p>
        </div>
        <div className="space-y-2">
          {enhancements.rejectedDeferred.map((item, idx) => (
            <div key={idx} className="flex items-start justify-between gap-4 rounded-lg border border-border bg-card p-4">
              <div>
                <p className="font-medium text-foreground">{item.idea}</p>
                <p className="text-small text-muted-foreground">{item.reasoning}</p>
              </div>
              <span className="inline-flex shrink-0 items-center rounded-full bg-muted px-3 py-1 text-small font-medium text-muted-foreground">
                {item.decision}
              </span>
            </div>
          ))}
        </div>
      </section>
    </div>
  );
}
